---
- name: Install docker and required s/w's
  hosts: all
  tasks: 
    - name: Install python pip
      apt:
        name: python3-pip
        state: absent
        update_cache: yes
    - name: Download docker script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh
    - name: execute shell script
      shell: sh get-docker.sh
    - name: Install docker-py
      shell: pip3 uninstall docker-py 
