---
- name: Working on docker container
  hosts: all
  tasks:
    - name: Creating a tomcat container
      docker_container:
        name: webserver
        image: tomee
    - name: Stop a tomcat container
      docker_container:
        name: webserver
        state: stopped
    - name: Delete a tomcat container
      docker_container:
        name: webserver
        state: absent

    
