---
- name: User creation
  hosts: 172.31.43.88
  tasks:
    - name: Creation of user
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
        home: "{{d}}"
        comment: "{{e}}"
        shell: "{{f}}"
