---
- name: Implementing tags
  hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: Install tree
      apt:
         name: tree
         state: present
         update_cache: yes
      tags: tree_installation
    - name: user creation
      user:
         name: navya
         password: brand
      tags: user_creation
    - name: copy passwd file
      copy:
        src: /etc/passwd
        dest: /tmp
    
