---
- name: Install s/w package
  hosts: all
  vars:
    - a: tree
    - b: present
    - c: yes
  tasks:
    - name: Install 
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
    
